config/routes.rb
Rails.application.routes.draw do

  root 'fotos#index'

  get 'fotos' => 'fotos#show', as: :show_user_photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
require 'flickraw'

  FlickRaw.api_key = ENV["KEY"]
  FlickRaw.shared_secret = ENV["SECRET"]

  def index

  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flickr_helper.rb
module FlickrHelper  
  #def user_photos(user_id, photo_count = 12)
  #  flickr = Flickr.new(File.join(RAILS_ROOT, 'config', 'flickr.yml'))
  #  flickr.photos.search(:user_id => user_id).values_at(0..(photo_count - 1))
  #end

  def user_photos(user_id, photo_count = 12)
    flickr.photos.search(user_id: user_id).to_a[0..(photo_count - 1)]
    #flickr.photos.search(:user_id => user_id).values_at(0..(photo_count - 1))
  end
  
  def render_flickr_sidebar_widget(user_id, photo_count = 12, columns = 2)
    begin
      photos = user_photos(user_id, photo_count).in_groups_of(2)
      render partial: '/flickr/sidebar_widget', locals: { photos: photos }
    rescue Exception
      render partial: '/flickr/unavailable'
    end
  end

  def render_flickr_sidebar(user_id = "129625689@N05", photo_count = 12, columns = 2)
    begin
      user_id = params[:flickr_id] unless params[:flickr_id].blank?
      photos = user_photos(user_id, photo_count).in_groups_of(6)
      render partial: '/flickr/sidebar_widget', locals: { photos: photos }
    rescue Exception
      render partial: '/flickr/unavailable'
    end
  end
end

app/views/flickr/_sidebar_widget.html.erb
<div class="flickr">
  <ul>
    <% photos.each do |row| %>
      <li>
      <% row.each do |p| %>
        <% if !p.nil? %>
          <% info = flickr.photos.getInfo(photo_id: p.id) %> 
          <%= link_to(image_tag(FlickRaw.url_q(info), :class => 'flickr_photo', :title => p.title, :border => 0), FlickRaw.url_photopage(info)) %>  

        <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>

</div>

app/views/flickr/_unavailable.html.erb
<h1>unavailable</h1>

app/views/fotos/index.html.erb
<h2>Search Photos by user id</h2>

<%= form_tag(show_user_photos_path, method: :get) do %>
  <%= label_tag(:flickr_id, "Flickr ID:") %>
  <%= text_field_tag(:flickr_id) %>
  <%= submit_tag("Search Photos") %>
<% end %>

app/views/fotos/show.html.erb
<h2>fotos</h2>
<%= render_flickr_sidebar %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MomentFreeze</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>